// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.5.0.0
//      Runtime Version:4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
namespace BowlingGameLib.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.5.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Bowling Game Scoring")]
    public partial class BowlingGameScoringFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "BowlingGameScoring.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Bowling Game Scoring", @"So that I can see my score
As a Bowler playing a game
I want to have my game scored

Description:
The game consists of 10 frames.  In each frame the player has
two opportunities to knock down 10 pins.  The score for the frame is the total
number of pins knocked down, plus bonuses for strikes and spares.

A spare is when the player knocks down all 10 pins in two tries.  The bonus for
that frame is the number of pins knocked down by the next roll.  So in frame 3
above, the score is 10 (the total number knocked down) plus a bonus of 5 (the
number of pins knocked down on the next roll.)

A strike is when the player knocks down all 10 pins on his first try.  The bonus
for that frame is the value of the next two balls rolled.

In the tenth frame a player who rolls a spare or strike is allowed to roll the extra
balls to complete the frame.  However no more than three balls can be rolled in
tenth frame.", GenerationTargetLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("0 Rolls")]
        public virtual void _0Rolls()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("0 Rolls", ((string[])(null)));
#line 24
 this.ScenarioSetup(scenarioInfo);
#line 25
  testRunner.Given("A new game");
#line 26
  testRunner.Then("My score should be 0");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1 roll")]
        public virtual void _1Roll()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1 roll", ((string[])(null)));
#line 28
 this.ScenarioSetup(scenarioInfo);
#line 29
  testRunner.Given("A new game");
#line 30
  testRunner.When("I make the following rolls: 2");
#line 31
  testRunner.Then("My score should be 2");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2 rolls")]
        public virtual void _2Rolls()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2 rolls", ((string[])(null)));
#line 33
 this.ScenarioSetup(scenarioInfo);
#line 34
  testRunner.Given("A new game");
#line 35
  testRunner.When("I make the following rolls: 6, 3");
#line 36
  testRunner.Then("My score should be 9");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("with no spares or strikes")]
        public virtual void WithNoSparesOrStrikes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("with no spares or strikes", ((string[])(null)));
#line 38
 this.ScenarioSetup(scenarioInfo);
#line 39
  testRunner.Given("A new game");
#line 40
  testRunner.When("I make the following rolls: 1, 4, 4, 5");
#line 41
  testRunner.Then("My score should be 14");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("a perfect game")]
        public virtual void APerfectGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("a perfect game", ((string[])(null)));
#line 43
 this.ScenarioSetup(scenarioInfo);
#line 44
  testRunner.Given("A new game");
#line 45
  testRunner.When("I make the following rolls: 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10");
#line 46
  testRunner.Then("My score should be 300");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("another perfect game")]
        public virtual void AnotherPerfectGame()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("another perfect game", ((string[])(null)));
#line 48
 this.ScenarioSetup(scenarioInfo);
#line 49
  testRunner.Given("A new game");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "roll"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
            table1.AddRow(new string[] {
                        "10"});
#line 50
  testRunner.When("I make the following rolls:", ((string)(null)), table1);
#line 64
  testRunner.Then("My score should be 300");
#line hidden
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("with spares and strikes")]
        public virtual void WithSparesAndStrikes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("with spares and strikes", ((string[])(null)));
#line 66
 this.ScenarioSetup(scenarioInfo);
#line 67
  testRunner.Given("A new game");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "roll"});
            table2.AddRow(new string[] {
                        "1"});
            table2.AddRow(new string[] {
                        "4"});
            table2.AddRow(new string[] {
                        "4"});
            table2.AddRow(new string[] {
                        "5"});
            table2.AddRow(new string[] {
                        "6"});
            table2.AddRow(new string[] {
                        "4"});
            table2.AddRow(new string[] {
                        "5"});
            table2.AddRow(new string[] {
                        "5"});
            table2.AddRow(new string[] {
                        "10"});
            table2.AddRow(new string[] {
                        "0"});
            table2.AddRow(new string[] {
                        "1"});
            table2.AddRow(new string[] {
                        "7"});
            table2.AddRow(new string[] {
                        "3"});
            table2.AddRow(new string[] {
                        "6"});
            table2.AddRow(new string[] {
                        "4"});
            table2.AddRow(new string[] {
                        "10"});
            table2.AddRow(new string[] {
                        "2"});
            table2.AddRow(new string[] {
                        "8"});
            table2.AddRow(new string[] {
                        "6"});
#line 68
  testRunner.When("I make the following rolls:", ((string)(null)), table2);
#line 89
  testRunner.Then("My score should be 133");
#line hidden
            testRunner.CollectScenarioErrors();
        }
    }
}
#endregion
